import {StyleSheet,Dimensions} from 'react-native';
const { width } = Dimensions.get("window");
const styles = StyleSheet.create({
  button: {
    marginTop : 10,
    marginBottom :10,
    width: 100,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#70F020',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    alignSelf: 'center',
    borderWidth:2,
    paddingLeft:5,
    paddingRight:5,
  },
  dropdownpicker: {
    alignItems: "center",
  	width: "80%",
  	borderRadius: 5,
  	paddingVertical: 8,
  	paddingHorizontal: 16,
  	borderColor: "rgba(0, 0, 0, 0.2)",
  	borderWidth: 1,
  	marginBottom: 8,
  	backgroundColor : "#fff"
  },
  mainmenubutton: {
    marginTop : 8,
    marginBottom :8,
    width: 300,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#70F020',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    alignSelf: 'center',
    borderWidth:2,
  },
  messageboardbutton: {
    marginTop : 2,
    marginBottom :2,
    width: 100,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#70F020',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    alignSelf: 'center',
    borderWidth:1,
    marginRight:10,
  },
  modalView: {
    alignItems: "center",
  	justifyContent: "center",
  	position: "absolute",
  	top: "50%",
  	left: "50%",
  	elevation: 5,
  	transform: [{ translateX: -(width * 0.4) },
  				{ translateY: -90 }],
  	height: 180,
    width: width * 0.8,
  	backgroundColor: "#FDFD96",
  	borderRadius: 15,
  	borderWidth: 3,
  },
  newtopicbutton: {
    marginTop : 2,
    marginBottom :2,
    width: 130,
    height: 30,
    borderRadius: 10,
    backgroundColor: '#70F020',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    alignSelf: 'center',
    borderWidth:1,
    marginRight:10,
  },
  newtopictextInput: {
   	width: "90%",
  	borderRadius: 5,
  	paddingVertical: 8,
  	paddingHorizontal: 16,
  	borderColor: "rgba(0, 0, 0, 0.2)",
  	borderWidth: 1,
  	marginBottom: 8,
  	backgroundColor : "#fff"
  },
  registerbutton: {
    marginTop : 20,
    marginBottom :20,
    width: 120,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#70F020',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    alignSelf: 'center',
    borderWidth:2,
    paddingLeft:5,
    paddingRight:5,
  },
  registertextInput: {
   	width: "82%",
   	borderRadius: 5,
  	paddingVertical: 8,
   	paddingHorizontal: 16,
   	marginLeft :10,
   	borderColor: "rgba(0, 0, 0, 0.2)",
   	borderWidth: 1,
   	marginBottom: 8,
   	backgroundColor : "#fff"
  },
  screen: {
  	flex: 1,
  	alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FDFD96",
  },
  textInput: {
  	width: "80%",
  	borderRadius: 5,
  	paddingVertical: 8,
  	paddingHorizontal: 16,
  	marginLeft :10,
  	borderColor: "rgba(0, 0, 0, 0.2)",
  	borderWidth: 1,
  	marginBottom: 8,
  	backgroundColor : "#fff"
  },
  title: {
    fontSize: 20,
    color:'purple'
  },
  topicmodalView: {
  	alignItems: "center",
  	justifyContent: "center",
  	position: "absolute",
  	top: "40%",
  	left: "46.5%",
  	elevation: 5,
  	transform: [{ translateX: -(width * 0.4) },
  				{ translateY: -90 }],
  	height: 370,
  	width: width * 0.85,
  	backgroundColor: "#FDFD96",
  	borderRadius: 15,
  	borderWidth: 3,
  },
  viewWrapper: {
  	flex: 1,
  	alignItems: "center",
  	justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
});
export default styles;